[2023-09-27 19:36:35,253] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:36:35,600] WARNING  * Debugger is active! - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:36:35,601] INFO  * Debugger PIN: 896-767-197 - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:36:39,065] INFO Coletando Rotas de Backbone - call_trace=/home/python/app/app.py L75  
[2023-09-27 19:36:39,069] INFO 172.30.0.1 - - [27/Sep/2023 19:36:39] "GET /rotas_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:36:50,668] INFO  * Detected change in '/home/python/app/app.py', reloading - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:36:50,737] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:36:51,077] WARNING  * Debugger is active! - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:36:51,078] INFO  * Debugger PIN: 896-767-197 - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:36:52,834] INFO Coletando Rotas de Backbone - call_trace=/home/python/app/app.py L75  
[2023-09-27 19:36:52,839] INFO 172.30.0.1 - - [27/Sep/2023 19:36:52] "GET /rotas_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:37:41,017] INFO 172.30.0.1 - - [27/Sep/2023 19:37:41] "[31m[1mPOST /rota_backbone HTTP/1.1[0m" 422 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:38:01,976] INFO Adicionando Rota de Backbone de nome: 'ROTA RIO DE JANEIRO - S√ÉO PAULO' - call_trace=/home/python/app/app.py L45  
[2023-09-27 19:38:01,998] INFO Adicionando Rota de Backbone: RotaBackbone(id=1, nome='ROTA RIO DE JANEIRO - S√ÉO PAULO', uf_ponta_a='RJ', cidade_ponta_a='RIO DE JANEIRO', uf_ponta_b='SP', cidade_ponta_b='S√ÉO PAULO') - call_trace=/home/python/app/app.py L53  
[2023-09-27 19:38:01,998] INFO 172.30.0.1 - - [27/Sep/2023 19:38:01] "POST /rota_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:38:19,339] INFO Coletando Rotas de Backbone - call_trace=/home/python/app/app.py L75  
[2023-09-27 19:38:19,340] INFO 1 Rotas de Backbone encontradas - call_trace=/home/python/app/app.py L85  
[2023-09-27 19:38:19,341] INFO 172.30.0.1 - - [27/Sep/2023 19:38:19] "GET /rotas_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:39:48,811] INFO  * Detected change in '/home/python/app/schemas/rota_backbone.py', reloading - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:39:48,879] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:39:49,232] WARNING  * Debugger is active! - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:39:49,233] INFO  * Debugger PIN: 896-767-197 - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:39:55,963] INFO Coletando Rotas de Backbone - call_trace=/home/python/app/app.py L75  
[2023-09-27 19:39:55,968] INFO 1 Rotas de Backbone encontradas - call_trace=/home/python/app/app.py L85  
[2023-09-27 19:39:55,969] INFO 172.30.0.1 - - [27/Sep/2023 19:39:55] "GET /rotas_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:39:57,044] INFO Coletando Rotas de Backbone - call_trace=/home/python/app/app.py L75  
[2023-09-27 19:39:57,045] INFO 1 Rotas de Backbone encontradas - call_trace=/home/python/app/app.py L85  
[2023-09-27 19:39:57,045] INFO 172.30.0.1 - - [27/Sep/2023 19:39:57] "GET /rotas_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:39:57,676] INFO Coletando Rotas de Backbone - call_trace=/home/python/app/app.py L75  
[2023-09-27 19:39:57,677] INFO 1 Rotas de Backbone encontradas - call_trace=/home/python/app/app.py L85  
[2023-09-27 19:39:57,677] INFO 172.30.0.1 - - [27/Sep/2023 19:39:57] "GET /rotas_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:41:04,006] INFO Adicionando Rota de Backbone de nome: 'ROTA RIO DE JANEIRO - BELO HORIZONTE' - call_trace=/home/python/app/app.py L45  
[2023-09-27 19:41:04,026] INFO Adicionando Rota de Backbone: RotaBackbone(id=2, nome='ROTA RIO DE JANEIRO - BELO HORIZONTE', uf_ponta_a='RJ', cidade_ponta_a='RIO DE JANEIRO', uf_ponta_b='MG', cidade_ponta_b='BELO HORIZONTE') - call_trace=/home/python/app/app.py L53  
[2023-09-27 19:41:04,026] INFO 172.30.0.1 - - [27/Sep/2023 19:41:04] "POST /rota_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:41:16,191] INFO Coletando Rotas de Backbone - call_trace=/home/python/app/app.py L75  
[2023-09-27 19:41:16,192] INFO 2 Rotas de Backbone encontradas - call_trace=/home/python/app/app.py L85  
[2023-09-27 19:41:16,192] INFO 172.30.0.1 - - [27/Sep/2023 19:41:16] "GET /rotas_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:44:57,530] INFO  * Detected change in '/home/python/app/schemas/rota_backbone.py', reloading - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:44:57,599] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:44:57,925] WARNING  * Debugger is active! - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:44:57,926] INFO  * Debugger PIN: 181-077-572 - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:45:00,019] INFO 172.30.0.1 - - [27/Sep/2023 19:45:00] "[35m[1mGET /openapi/swagger HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:45:00,034] INFO 172.30.0.1 - - [27/Sep/2023 19:45:00] "GET /openapi/swagger?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:45:00,037] INFO 172.30.0.1 - - [27/Sep/2023 19:45:00] "GET /openapi/swagger?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:45:00,052] INFO 172.30.0.1 - - [27/Sep/2023 19:45:00] "GET /openapi/swagger?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:45:00,068] INFO 172.30.0.1 - - [27/Sep/2023 19:45:00] "[36mGET /openapi/swagger?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:09,221] INFO  * Detected change in '/home/python/app/schemas/rota_backbone.py', reloading - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:09,297] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:09,660] WARNING  * Debugger is active! - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:09,660] INFO  * Debugger PIN: 896-767-197 - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:10,565] INFO 172.30.0.1 - - [27/Sep/2023 19:46:10] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:10,587] INFO 172.30.0.1 - - [27/Sep/2023 19:46:10] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:10,588] INFO 172.30.0.1 - - [27/Sep/2023 19:46:10] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:10,588] INFO 172.30.0.1 - - [27/Sep/2023 19:46:10] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:10,719] INFO 172.30.0.1 - - [27/Sep/2023 19:46:10] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:10,722] INFO 172.30.0.1 - - [27/Sep/2023 19:46:10] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:46:23,814] INFO Coletando Rotas de Backbone - call_trace=/home/python/app/app.py L75  
[2023-09-27 19:46:23,819] INFO 2 Rotas de Backbone encontradas - call_trace=/home/python/app/app.py L85  
[2023-09-27 19:46:23,820] INFO 172.30.0.1 - - [27/Sep/2023 19:46:23] "GET /rotas_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:48:18,194] INFO  * Detected change in '/home/python/app/schemas/rota_backbone.py', reloading - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:48:18,272] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 19:48:18,625] WARNING  * Debugger is active! - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
