[2023-09-27 20:15:24,620] INFO Rota de Backbone encontrada: RotaBackbone(id=3, nome='ROTA RIO DE JANEIRO - VIT√ìRIA', descricao='Enlace de fibra √≥tica interligando as cidades do Rio e de Vit√≥ria, seguindo o tra√ßado da BR 101', uf_ponta_a='RJ', cidade_ponta_a='RIO DE JANEIRO', uf_ponta_b='ES', cidade_ponta_b='VIT√ìRIA') - call_trace=/home/python/app/app.py L109 
[2023-09-27 20:15:24,621] INFO 172.30.0.1 - - [27/Sep/2023 20:15:24] "GET /rota_backbone?id=3 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:15:30,595] INFO Coletando dados sobre a Rota de Backbone #2 - call_trace=/home/python/app/app.py L97  
[2023-09-27 20:15:30,596] INFO Rota de Backbone encontrada: RotaBackbone(id=2, nome='ROTA RIO DE JANEIRO - BELO HORIZONTE', descricao='Enlace de fibra √≥tica interligando as cidades do Rio e de Belo Horizonte, seguindo o tra√ßado da BR 040', uf_ponta_a='RJ', cidade_ponta_a='RIO DE JANEIRO', uf_ponta_b='MG', cidade_ponta_b='BELO HORIZONTE') - call_trace=/home/python/app/app.py L109 
[2023-09-27 20:15:30,597] INFO 172.30.0.1 - - [27/Sep/2023 20:15:30] "GET /rota_backbone?id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:15:35,995] INFO Coletando dados sobre a Rota de Backbone #1 - call_trace=/home/python/app/app.py L97  
[2023-09-27 20:15:35,996] INFO Rota de Backbone encontrada: RotaBackbone(id=1, nome='ROTA RIO DE JANEIRO - S√ÉO PAULO', descricao='Enlace de fibra √≥tica interligando as cidades do Rio e de S√£o Paulo, seguindo o tra√ßado da Via Dutra', uf_ponta_a='RJ', cidade_ponta_a='RIO DE JANEIRO', uf_ponta_b='SP', cidade_ponta_b='S√ÉO PAULO') - call_trace=/home/python/app/app.py L109 
[2023-09-27 20:15:35,997] INFO 172.30.0.1 - - [27/Sep/2023 20:15:35] "GET /rota_backbone HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:21:53,474] INFO  * Detected change in '/home/python/app/schemas/rota_backbone.py', reloading - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:21:53,903] WARNING  * Debugger is active! - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:21:53,903] INFO  * Debugger PIN: 896-767-197 - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:21:57,922] INFO  * Detected change in '/home/python/app/app.py', reloading - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:21:58,343] WARNING  * Debugger is active! - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:21:58,344] INFO  * Debugger PIN: 896-767-197 - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:23:32,758] INFO 172.30.0.1 - - [27/Sep/2023 20:23:32] "[31m[1mPOST /rota_backbone HTTP/1.1[0m" 422 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
[2023-09-27 20:24:08,886] INFO  * Detected change in '/home/python/app/schemas/rota_backbone.py', reloading - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L187 
